# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffb5b51c23d29aa2b8f0cdb9de13ac244dec15a6b584ee7638975535b33f2b67eed6d4db51cff95ae8deaa2b44e7424de113899f020595f8baeeee3e288b1eda

test:
  secret_key_base: de5c2dcdf7f97bba6052c4ed40b360f902caf93269dd8c014fb4eeefbb96a9dc43502dafd89e19bf1ca7fa7eeeb05b168fa1b1df5664910789eba1b7f2ea687e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
